name: Terraform Apply

on:
    push:
        branches: [main]

jobs:
    apply:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2
        
        - name: Setup terraform 
          uses: hashicorp/setup-terraform@v3 
        
        - name: Run terraform init
          run: terraform init
        
        - name: Run terraform apply
          run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"
